export const FETCH_DIAGNOSES_REQUEST = 'HomePage/FETCH_DIAGNOSES_REQUEST';
export const FETCH_DIAGNOSES_SUCCESS = 'HomePage/FETCH_DIAGNOSES_SUCCESS';
export const FETCH_DIAGNOSES_ERROR = 'HomePage/FETCH_DIAGNOSES_ERROR';
