export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';

export const FETCH_DIAGNOSES_REQUEST = 'HomePage/FETCH_DIAGNOSES_REQUEST';
export const FETCH_DIAGNOSES_SUCCESS = 'HomePage/FETCH_DIAGNOSES_SUCCESS';

export const CREATE_DIAGNOSIS_REQUEST = 'HomePage/CREATE_DIAGNOSIS_REQUEST';
export const CREATE_DIAGNOSIS_SUCCESS = 'HomePage/CREATE_DIAGNOSIS_SUCCESS';
